apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
     name: django-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
      name: propsamc-django
      app:  propsamc-frontend
