apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
     name: django-service
     app: propsamc-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30006